[package]
name = "rrg"
description = "Rust rewrite of GRR."
version = "0.1.0"
authors = ["Łukasz Hanuszczak <hanuszczak@google.com>"]
edition = "2018"

[dependencies]
ioctls = {version = "0.5.1"}
fleetspeak = { version = "0.1.2" }
humantime = { version = "2.0.0" }
log = { version = "0.4.8" }
prost = { version = "0.6.1" }
prost-types = { version = "0.6.1" }
rrg-proto = { path = "proto/" }
simplelog = { version = "0.7.6" }
structopt = { version = "0.3.12" }
netstat2 = { version = "0.8.1" }
sysinfo = { version = "0.14.1" }
xattr = { version = "0.2.2" }
tempfile = { version = "3.1.0" }
